name: Build CI

on:
  push:
    branches:
      - 'main'            # Default branch
      - 'feature-**'      # Feature branches
      - '[0-9]+.[0-9]+.x' # Release branches
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - 'main'            # Default branch
      - 'feature-**'      # Feature branches
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions: { }

jobs:
  call-build:
    uses: ./.github/workflows/_meta-build.yaml
    with:
      app-version: "snapshot"
      publish-container: ${{ github.ref_name == 'main' || startsWith(github.ref_name, 'feature-') }} # publish container only for commit on main or feature branch
      ref-name: ${{ github.ref_name }}
      src_profile: 'license-compliance'
      src_type: 'java'
      artifact_name: 'artifact-package'
    permissions:
      security-events: write # Required to upload trivy's SARIF output
    secrets:
      registry-0-usr: ${{ secrets.HUB_USERNAME }}
      registry-0-psw: ${{ secrets.HUB_ACCESSS_TOKEN }}
