# This workflow is responsible to build and publish a release build
# It triggers once a new GitHub Release is published
name: Publish CI

on:
  release:
    types:
      - released

permissions: { }

jobs:
  read-version:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      version: ${{ steps.parse.outputs.version }}
    steps:
      - name: Assert ref type
        run: |-
          if [[ "$GITHUB_REF_TYPE" != "tag" ]]; then
            echo "::error::Publishing is only supported for tags!"
            exit 1
          fi
      - name: Parse Version from Tag
        id: parse
        run: |-
          VERSION=${{ github.ref_name }}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      
  call-build:
    needs:
      - read-version
    uses: ./.github/workflows/_meta-build.yaml
    with:
      app-version: ${{ needs.read-version.outputs.version }}
      publish-container: true
      ref-name: ${{ github.ref_name }}
      src_profile: 'license-compliance'
      artifact_name: 'artifact-package'
    permissions:
      security-events: write # Required to upload trivy's SARIF output
    secrets:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

  update-github-release:
    runs-on: ubuntu-latest
    needs:
      - read-version
      - call-build
    steps:
      - name: Checkout Repository #required to use gh CLI
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v4.2.2

      - name: Download Artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # tag=v5.0.0
        with:
          name: 'artifact-package'
          path: target

      - name: list files
        run: ls -la target

      - name: Update release adding package and SBOM
        env:
         GH_TOKEN: ${{ secrets.BOT_PUBLISH_TOKEN }} #personal access token, with repo scope
        run: |
           gh release upload ${{ needs.read-version.outputs.version }} \
             target/*.* \
             --clobber

            
