# This workflow is responsible to build and publish a release build
# It triggers once a new GitHub Release is published
name: Publish CI

on:
  release:
    types:
      - released
  #workflow_dispatch:

permissions: { }

jobs:
  read-version:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      version: ${{ steps.parse.outputs.version }}
    steps:
      - name: Assert ref type
        run: |-
          if [[ "$GITHUB_REF_TYPE" != "tag" ]]; then
            echo "::error::Publishing is only supported for tags!"
            exit 1
          fi
      - name: Parse Version from Tag
        id: parse
        run: |-
          VERSION=${{github.ref_name }}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      
  call-build:
    needs:
      - read-version
    uses: ./.github/workflows/_meta-build.yaml
    with:
      app-version: ${{ needs.read-version.outputs.version }}
      publish-container: true
      ref-name: ${{ github.ref_name }}
      src_profile: 'license-compliance'
    permissions:
      security-events: write # Required to upload trivy's SARIF output
    secrets:
      registry-0-usr: ${{ secrets.HUB_USERNAME }}
      registry-0-psw: ${{ secrets.HUB_ACCESSS_TOKEN }}

  update-github-release:
    runs-on: ubuntu-latest
    needs:
      - read-version
      - call-build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # tag=v4.3.0
        with:
          name: assembled-wars
          path: target

      - name: list files
        run: ls -la target

      - name: Create or update release
        env:
         GH_TOKEN: ${{ secrets.BOT_PUBLISH_TOKEN }}
        run: gh release upload ${{ needs.read-version.outputs.version }} --clobber target/bom.json

      #- name: Release
      #  uses: softprops/action-gh-release@v2
      #  with:
      #    token: ${{ secrets.BOT_PUBLISH_TOKEN }}
      #    files: |
      #      target/bom.json
            
      #- name: Update Release
      #  env:
      #    GH_TOKEN: ${{ secrets.BOT_PUBLISH_TOKEN }}
      #  run: |-
      #    gh release upload ${{ needs.read-version.outputs.version }} \
      #      --clobber \
      #      target/bom.json

#target/hello-springboot*.jar \
            
