name: Generate SBOM

on:
  push:
    branches:
      - 'master'          # Default branch
      - 'feature-**'      # Feature branches
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

permissions: { }

jobs:
  call-build:
    uses: cleansefbk/infra-ci/.github/workflows/cdxgen_sbom.yml@main
    with:
      src_repository: ${{ github.repository }}
      src_branch: ${{ github.ref_name }}
      src_type: 'java'
      src_profile: 'license-compliance'
    permissions:
      security-events: write # Required to upload trivy's SARIF output
    secrets:
      registry-0-usr: ${{ secrets.HUB_USERNAME }}
      registry-0-psw: ${{ secrets.HUB_ACCESSS_TOKEN }}

    
